version: '3.8'

services:
  vps-firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: vps-firefox
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # Authentication for accessing the remote Firefox browser
      - CUSTOM_USER=admin
      - PASSWORD=ChangeMeSecure123!
    volumes:
      - ./config:/config
      - ./policies.json:/usr/lib/firefox/distribution/policies.json:ro
      - ./policies.json:/etc/firefox/policies/policies.json:ro
    ports:
      # Port 3000 for KasmVNC Web GUI (Direct & SSH Tunnel)
      - "3000:3000"
      - "3001:3001"
    shm_size: "2gb" # Firefox shared memory for rendering and media

    restart: unless-stopped

